services:
  db:
    image: postgres:16
    container_name: ban_postgres
    environment:
      POSTGRES_USER: ban_user
      POSTGRES_PASSWORD: ban_pass
      POSTGRES_DB: ban_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
