services:
  db_ban:
    image: postgres:17
    environment:
      POSTGRES_DB: db_ban         
      POSTGRES_USER: ban     
      POSTGRES_PASSWORD: ban123
    ports:
      - "5432:5432"
    volumes:
      - pgdata: 




